name: XLSX-split Building

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-XLSX-split:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller argparse openpyxl --ignore-installed

      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import csv,os,codecs,configparser,argparse,openpyxl --strip XLSX-split.py --distpath dist/${{ matrix.os }}

      - name: Upload artifact (Linux)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-split_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-22.04/XLSX-split

      - name: Upload artifact (Windows)
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-split_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/XLSX-split.exe

  build-XLSX-SheetCutter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller openpyxl --ignore-installed

      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import csv,os,codecs,configparser,openpyxl --strip XLSX-SheetCutter.py --distpath dist/${{ matrix.os }}

      - name: Upload artifact (Linux)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-SheetCutter_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-22.04/XLSX-SheetCutter

      - name: Upload artifact (Windows)
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-SheetCutter_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/XLSX-SheetCutter.exe

  build-XLSX-SheetMerger:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
          - build: windows
            os: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Set commit message
        id: set_commit
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            echo "COMMIT_MESSAGE=$(git log --format=%B -1)" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-2019" ]; then
            commit_message=$(git log --format=%B -1)
            echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.11/x64

      - name: Install dependencies
        run: |
          python -m pip install pyinstaller openpyxl --ignore-installed

      - name: Build executable
        run: |
          pyinstaller --onefile --hidden-import csv,os,codecs,configparser,openpyxl --strip XLSX-SheetMerger.py --distpath dist/${{ matrix.os }}

      - name: Upload artifact (Linux)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-SheetMerger_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/ubuntu-22.04/XLSX-SheetMerger

      - name: Upload artifact (Windows)
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/upload-artifact@v3
        with:
          name: build_XLSX-SheetMerger_${{ matrix.os }}_v${{ env.COMMIT_MESSAGE }}
          path: dist/windows-2019/XLSX-SheetMerger.exe
